using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TravelPathways.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddMissingTenantIndexes : Migration
    {
        // NOTE: this migration was originally auto-generated by `dotnet ef migrations add`, which
        // also picked up a large amount of pre-existing drift between AppDbContextModelSnapshot.cs
        // and the real migration history (the snapshot was missing ~15 entities' worth of state that
        // earlier migrations, e.g. AddDriversAndAssignments/AddPackageLogs, had already applied).
        // That drift has been corrected as a side effect of regenerating the snapshot, but this
        // migration's Up()/Down() were hand-trimmed to ONLY add the missing TenantId indexes below —
        // using raw SQL with IF NOT EXISTS/IF EXISTS guards since the drift above means we cannot
        // fully trust that no index of the same name/shape already exists via a manual script.

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Vehicles_TenantId\" ON \"Vehicles\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_VehiclePricing_TenantId\" ON \"VehiclePricing\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_TransportCompanies_TenantId\" ON \"TransportCompanies\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Tasks_TenantId_UserId\" ON \"Tasks\" (\"TenantId\", \"UserId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Reservations_TenantId_CreatedAt\" ON \"Reservations\" (\"TenantId\", \"CreatedAt\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Payments_TenantId_CreatedAt\" ON \"Payments\" (\"TenantId\", \"CreatedAt\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Leaves_TenantId_UserId\" ON \"Leaves\" (\"TenantId\", \"UserId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Hotels_TenantId\" ON \"Hotels\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_EmployeeSalary_TenantId_UserId\" ON \"EmployeeSalary\" (\"TenantId\", \"UserId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_DestinationMaster_TenantId\" ON \"DestinationMaster\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_DayItineraries_TenantId\" ON \"DayItineraries\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_AccommodationRates_TenantId\" ON \"AccommodationRates\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_PackageDriverAssignments_TenantId\" ON \"PackageDriverAssignments\" (\"TenantId\") WHERE \"IsDeleted\" = false;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_PackageLogs_TenantId_CreatedAt\" ON \"PackageLogs\" (\"TenantId\", \"CreatedAt\");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Vehicles_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_VehiclePricing_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_TransportCompanies_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Tasks_TenantId_UserId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Reservations_TenantId_CreatedAt\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Payments_TenantId_CreatedAt\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Leaves_TenantId_UserId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_Hotels_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_EmployeeSalary_TenantId_UserId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_DestinationMaster_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_DayItineraries_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_AccommodationRates_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_PackageDriverAssignments_TenantId\";");
            migrationBuilder.Sql("DROP INDEX IF EXISTS \"IX_PackageLogs_TenantId_CreatedAt\";");
        }
    }
}
